### ISSUE TITLE
Issues using the provider via Linux/amd64

### ISSUE THREAD

**Issue by SeanSanker** [pulumiverse/pulumi-doppler#5]
When attempting to use the provider via CircleCI using a `node` docker image, I get this error:
```
    Underlying error: error downloading plugin doppler to file: failed to download plugin: doppler-0.0.10: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-doppler-v0.0.10-linux-amd64.tar.gz
```

I'm not sure if 
* it's picking up the wrong version 
* the linux/amd64 provider isn't configured in the project
* the package isn't deployed to the CDN
* (something else)

Any assistance would be greatly appreciated.
Thank you!

**Comment by rawkode** [comment]
I think your version of Pulumi may be a little old, perhaps?

Older versions of Pulumi don't know to check the JSON schema for the download URL, which may be why you're getting requests for `https://get.pulumi.com`

Can you confirm the version?

**Comment by SeanSanker** [comment]
Thank you for your help!

I've bumped our CircleCI orb `pulumi/pulumi` to `2.1.0` and `@pulumi/pulumi` package to `"^3.51.1"` and I'm still getting the error. 

Notes: 
We use the latest version of pulumi (currently `v3.51.0`) for the `pulumi/login` step.
We're using the automation API for the update.

For similar plugins, (aws, random, auth0), we use `pulumi plugin install resource <name> <version>`. 
I attempted that for Doppler with the output: 
```
#!/bin/bash -eo pipefail
pulumi plugin install resource doppler v0.0.10

[resource plugin doppler-0.0.10] installing
error: [resource plugin doppler-0.0.10] downloading from : failed to download plugin: doppler-0.0.10: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-doppler-v0.0.10-linux-amd64.tar.gz

Exited with code exit status 255

CircleCI received exit code 255
```

**Comment by rawkode** [comment]
OK. I'm getting this now too. Though it's intermittent. Let's hand over to @ringods from Pulumi to assist.

**Comment by rawkode** [comment]
Related: https://github.com/pulumi/pulumi/issues/11527

**Comment by ringods** [comment]
@SeanSanker can you try adding this to your Pulumi plugin install instruction:

`--server github://api.github.com/pulumiverse`

**Comment by rawkode** [comment]
I don’t believe either of us are installing plugins manually, this is a Pulumi CLI bug
