### ISSUE TITLE
Update link to get proper api keys

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-doppler#6]
Hello @rawkode,

Can you make the same change here as done in the `registry` repo?

https://github.com/pulumi/registry/pull/2322/files#diff-c9b647f7cd74305e8bb517db13d3171d9adaa3e8a4802c511c19a35bfbdae8bb

Pointing to a protected profile page leads to an HTTP error which impacts our SEO.

**Comment by rawkode** [comment]
Sorry, I don't use Pulumi any more.

**Comment by ringods** [comment]
@rawkode I guess we search for another maintainer then?

**Comment by ringods** [comment]
Fixed in 7ec4aa809f2d8c129f5bfb7c06baae88c6de61de
