### ISSUE TITLE
Can we update to latest doppler API?

### ISSUE THREAD

**Issue by will-wang-oleria** [pulumiverse/pulumi-doppler#7]

**Comment by ringods** [comment]
Status update: the provider is updated to

* use the latest `pulumi-terraform-bridge`
* small update to upstream TF provider version 1.1.7 (from 1.1.3)

Published as [v0.1.2](https://www.pulumi.com/registry/packages/doppler/).

**NOTE:**

Resource `doppler.Config` is renamed to `doppler.BranchConfig` to no longer conflict with a `Config` class generated in some of our language SDKs. I added a type alias which means that if you created `Config` resources with an older version, upgrade to this newer version, then you only have to update the type name in your code. When running Pulumi, it should **not** lead to the resource being recreated.

**Comment by ringods** [comment]
Version [0.7.0](https://github.com/pulumiverse/pulumi-doppler/releases/tag/v0.7.0) of this provider is in sync with upstream TF provider v1.7.1.
